### ISSUE TITLE
No Actions?

### ISSUE THREAD

**Issue by Volk3rDE** [Dimithrandir/godot_2d_hex_map_nav_demo#1]
Hello,
first of all thanks for sharing :)
I imported it and got 2 warnings:
###
1# The argument 'delta' is never used in the function '_physics_process'. If this is intended, prefix it with an underscore: '_delta'
2# The argument 'event' is never used in the function '_input'. If this is intended, prefix it with an underscore: '_event'
###
everything is fine when started, but it doesn't respond to inputs.
Can you help activate the function?

Best regards
People
PS: Its Translated Text, Sorry <3

**Comment by Dimithrandir** [comment]
Hello,
Sorry for the delayed response.

Thank you for your comment on the warnings, it's always best to keep things clean.
I have already pushed the changes and the new version should be available in the Godot asset library once it's approved.

As for the inputs, the only custom action used is "**click**", which responds to **right** mouse button click event.
It is [handled in the Player.gd](https://github.com/Dimithrandir/godot_2d_hex_map_nav_demo/blob/45889460c6eabfca5280c6ca0ad90eece181891c/scripts/Player.gd#L21) script.
The [_input method in TileMap.gd](https://github.com/Dimithrandir/godot_2d_hex_map_nav_demo/blob/45889460c6eabfca5280c6ca0ad90eece181891c/scripts/TileMap.gd#L16) is only used to update the labels with the player's position on the tile map. 
I am not sure if this is the best practice, but it's suitable for a simple demo project.

I hope you've found this project useful. 
Let me know if I misunderstood the issue. 

Cheers! :wave:

**Comment by Volk3rDE** [comment]
Hello and thank you, that's exactly what I meant. This will help me a lot as a beginner to understand this language and structure.
Wonderful work, thanks and keep having fun with Godot...

**Comment by Dimithrandir** [comment]
Thank you.

I hope this project will be of some assistance to you.

Have fun and good luck!
